SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

USE `pyo`;

insert into comments (Comment, Comment_ID, User_ID) values ('Synergized multi-tasking success', 1, '23');
insert into comments (Comment, Comment_ID, User_ID) values ('Multi-layered tangible time-frame', 2, '5');
insert into comments (Comment, Comment_ID, User_ID) values ('Enterprise-wide non-volatile data-warehouse', 3, '45');
insert into comments (Comment, Comment_ID, User_ID) values ('Optional homogeneous database', 4, '38');
insert into comments (Comment, Comment_ID, User_ID) values ('Programmable bandwidth-monitored archive', 5, '41');
insert into comments (Comment, Comment_ID, User_ID) values ('Reverse-engineered bandwidth-monitored Graphical User Interface', 6, '37');
insert into comments (Comment, Comment_ID, User_ID) values ('Business-focused encompassing encryption', 7, '24');
insert into comments (Comment, Comment_ID, User_ID) values ('Assimilated demand-driven contingency', 8, '10');
insert into comments (Comment, Comment_ID, User_ID) values ('Team-oriented global capability', 9, '4');
insert into comments (Comment, Comment_ID, User_ID) values ('Object-based executive utilisation', 10, '8');
insert into comments (Comment, Comment_ID, User_ID) values ('Versatile client-server system engine', 11, '48');
insert into comments (Comment, Comment_ID, User_ID) values ('Grass-roots leading edge strategy', 12, '2');
insert into comments (Comment, Comment_ID, User_ID) values ('Down-sized context-sensitive portal', 13, '11');
insert into comments (Comment, Comment_ID, User_ID) values ('Mandatory secondary middleware', 14, '43');
insert into comments (Comment, Comment_ID, User_ID) values ('Synergistic empowering help-desk', 15, '19');
insert into comments (Comment, Comment_ID, User_ID) values ('Cloned dedicated policy', 16, '29');
insert into comments (Comment, Comment_ID, User_ID) values ('Innovative high-level product', 17, '26');
insert into comments (Comment, Comment_ID, User_ID) values ('Versatile methodical frame', 18, '33');
insert into comments (Comment, Comment_ID, User_ID) values ('Switchable holistic archive', 19, '25');
insert into comments (Comment, Comment_ID, User_ID) values ('Function-based explicit flexibility', 20, '1');
insert into comments (Comment, Comment_ID, User_ID) values ('Public-key optimal strategy', 21, '12');
insert into comments (Comment, Comment_ID, User_ID) values ('Organized homogeneous circuit', 22, '28');
insert into comments (Comment, Comment_ID, User_ID) values ('User-friendly logistical internet solution', 23, '18');
insert into comments (Comment, Comment_ID, User_ID) values ('Reverse-engineered global array', 24, '49');
insert into comments (Comment, Comment_ID, User_ID) values ('Profound bottom-line methodology', 25, '31');
insert into comments (Comment, Comment_ID, User_ID) values ('Devolved bi-directional strategy', 26, '7');
insert into comments (Comment, Comment_ID, User_ID) values ('Inverse multimedia project', 27, '16');
insert into comments (Comment, Comment_ID, User_ID) values ('Expanded 3rd generation infrastructure', 28, '34');
insert into comments (Comment, Comment_ID, User_ID) values ('Universal directional leverage', 29, '9');
insert into comments (Comment, Comment_ID, User_ID) values ('Fully-configurable exuding database', 30, '46');
insert into comments (Comment, Comment_ID, User_ID) values ('Managed demand-driven model', 31, '21');
insert into comments (Comment, Comment_ID, User_ID) values ('Organic tangible groupware', 32, '36');
insert into comments (Comment, Comment_ID, User_ID) values ('Managed tertiary budgetary management', 33, '22');
insert into comments (Comment, Comment_ID, User_ID) values ('Reduced fresh-thinking definition', 34, '13');
insert into comments (Comment, Comment_ID, User_ID) values ('Self-enabling 3rd generation focus group', 35, '30');
insert into comments (Comment, Comment_ID, User_ID) values ('Implemented homogeneous process improvement', 36, '44');
insert into comments (Comment, Comment_ID, User_ID) values ('Optional methodical moratorium', 37, '32');
insert into comments (Comment, Comment_ID, User_ID) values ('Business-focused static adapter', 38, '17');
insert into comments (Comment, Comment_ID, User_ID) values ('Reverse-engineered foreground concept', 39, '6');
insert into comments (Comment, Comment_ID, User_ID) values ('Synergized solution-oriented middleware', 40, '20');
insert into comments (Comment, Comment_ID, User_ID) values ('Persistent high-level software', 41, '39');
insert into comments (Comment, Comment_ID, User_ID) values ('Customizable multi-tasking budgetary management', 42, '35');
insert into comments (Comment, Comment_ID, User_ID) values ('Public-key holistic hardware', 43, '47');
insert into comments (Comment, Comment_ID, User_ID) values ('Diverse cohesive interface', 44, '15');
insert into comments (Comment, Comment_ID, User_ID) values ('Innovative hybrid budgetary management', 45, '27');
insert into comments (Comment, Comment_ID, User_ID) values ('Quality-focused non-volatile forecast', 46, '40');
insert into comments (Comment, Comment_ID, User_ID) values ('Compatible encompassing productivity', 47, '50');
insert into comments (Comment, Comment_ID, User_ID) values ('Automated analyzing architecture', 48, '3');
insert into comments (Comment, Comment_ID, User_ID) values ('Exclusive optimizing neural-net', 49, '42');
insert into comments (Comment, Comment_ID, User_ID) values ('Multi-layered clear-thinking initiative', 50, '14');
insert into comments (Comment, Comment_ID, User_ID) values ('User-centric foreground frame', 51, '44');
insert into comments (Comment, Comment_ID, User_ID) values ('Decentralized discrete success', 52, '24');
insert into comments (Comment, Comment_ID, User_ID) values ('Phased zero tolerance encryption', 53, '5');
insert into comments (Comment, Comment_ID, User_ID) values ('Public-key web-enabled throughput', 54, '7');
insert into comments (Comment, Comment_ID, User_ID) values ('Future-proofed bifurcated time-frame', 55, '14');
insert into comments (Comment, Comment_ID, User_ID) values ('Vision-oriented methodical Graphic Interface', 56, '26');
insert into comments (Comment, Comment_ID, User_ID) values ('Robust asymmetric protocol', 57, '49');
insert into comments (Comment, Comment_ID, User_ID) values ('Advanced asynchronous function', 58, '40');
insert into comments (Comment, Comment_ID, User_ID) values ('Sharable high-level migration', 59, '3');
insert into comments (Comment, Comment_ID, User_ID) values ('Visionary multimedia standardization', 60, '21');
insert into comments (Comment, Comment_ID, User_ID) values ('Intuitive actuating system engine', 61, '16');
insert into comments (Comment, Comment_ID, User_ID) values ('Programmable zero administration architecture', 62, '19');
insert into comments (Comment, Comment_ID, User_ID) values ('Pre-emptive client-server artificial intelligence', 63, '28');
insert into comments (Comment, Comment_ID, User_ID) values ('Compatible motivating matrix', 64, '11');
insert into comments (Comment, Comment_ID, User_ID) values ('Upgradable disintermediate support', 65, '38');
insert into comments (Comment, Comment_ID, User_ID) values ('Organized solution-oriented implementation', 66, '17');
insert into comments (Comment, Comment_ID, User_ID) values ('Proactive full-range migration', 67, '10');
insert into comments (Comment, Comment_ID, User_ID) values ('Total contextually-based approach', 68, '15');
insert into comments (Comment, Comment_ID, User_ID) values ('Right-sized bandwidth-monitored help-desk', 69, '23');
insert into comments (Comment, Comment_ID, User_ID) values ('Fundamental fresh-thinking neural-net', 70, '48');
insert into comments (Comment, Comment_ID, User_ID) values ('Automated system-worthy archive', 71, '20');
insert into comments (Comment, Comment_ID, User_ID) values ('Synergistic next generation extranet', 72, '13');
insert into comments (Comment, Comment_ID, User_ID) values ('Assimilated disintermediate time-frame', 73, '34');
insert into comments (Comment, Comment_ID, User_ID) values ('Cloned multi-state conglomeration', 74, '35');
insert into comments (Comment, Comment_ID, User_ID) values ('De-engineered exuding frame', 75, '9');
insert into comments (Comment, Comment_ID, User_ID) values ('Balanced bandwidth-monitored solution', 76, '2');
insert into comments (Comment, Comment_ID, User_ID) values ('Future-proofed disintermediate adapter', 77, '39');
insert into comments (Comment, Comment_ID, User_ID) values ('Quality-focused dynamic groupware', 78, '30');
insert into comments (Comment, Comment_ID, User_ID) values ('Cloned attitude-oriented projection', 79, '29');
insert into comments (Comment, Comment_ID, User_ID) values ('Centralized logistical instruction set', 80, '41');
insert into comments (Comment, Comment_ID, User_ID) values ('Intuitive tangible moderator', 81, '22');
insert into comments (Comment, Comment_ID, User_ID) values ('Ergonomic grid-enabled support', 82, '18');
insert into comments (Comment, Comment_ID, User_ID) values ('Face to face global capacity', 83, '42');
insert into comments (Comment, Comment_ID, User_ID) values ('Distributed client-server Graphical User Interface', 84, '6');
insert into comments (Comment, Comment_ID, User_ID) values ('Public-key 24/7 methodology', 85, '1');
insert into comments (Comment, Comment_ID, User_ID) values ('Profound optimizing secured line', 86, '32');
insert into comments (Comment, Comment_ID, User_ID) values ('Centralized user-facing contingency', 87, '4');
insert into comments (Comment, Comment_ID, User_ID) values ('Networked multimedia monitoring', 88, '43');
insert into comments (Comment, Comment_ID, User_ID) values ('Enterprise-wide cohesive budgetary management', 89, '33');
insert into comments (Comment, Comment_ID, User_ID) values ('Business-focused system-worthy framework', 90, '37');
insert into comments (Comment, Comment_ID, User_ID) values ('Distributed coherent emulation', 91, '31');
insert into comments (Comment, Comment_ID, User_ID) values ('Ameliorated eco-centric info-mediaries', 92, '25');
insert into comments (Comment, Comment_ID, User_ID) values ('Upgradable solution-oriented groupware', 93, '8');
insert into comments (Comment, Comment_ID, User_ID) values ('Balanced methodical firmware', 94, '12');
insert into comments (Comment, Comment_ID, User_ID) values ('Organic full-range forecast', 95, '36');
insert into comments (Comment, Comment_ID, User_ID) values ('Realigned local architecture', 96, '27');
insert into comments (Comment, Comment_ID, User_ID) values ('Ergonomic mobile challenge', 97, '50');
insert into comments (Comment, Comment_ID, User_ID) values ('Vision-oriented client-driven contingency', 98, '46');
insert into comments (Comment, Comment_ID, User_ID) values ('Team-oriented optimizing challenge', 99, '47');
insert into comments (Comment, Comment_ID, User_ID) values ('Total stable portal', 100, '45');
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 1);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 2);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 3);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 4);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 5);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 6);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 7);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 8);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 9);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 10);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 11);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 12);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 13);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 14);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 15);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 16);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 17);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 18);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 19);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 20);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 21);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 22);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 23);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 24);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 25);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 26);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 27);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 28);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 29);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 30);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 31);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 32);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 33);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 34);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 35);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 36);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 37);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 38);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 39);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 40);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 41);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 42);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 43);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 44);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 45);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 46);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 47);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 48);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 49);
insert into comments (Comment, Comment_ID, User_ID) values (null, null, 50);

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;