insert into MOCK_DATA (Genre, Genre_ID) values ('ante ipsum', 1);
insert into MOCK_DATA (Genre, Genre_ID) values ('iaculis justo in', 2);
insert into MOCK_DATA (Genre, Genre_ID) values ('pede lobortis', 3);
insert into MOCK_DATA (Genre, Genre_ID) values ('mattis', 4);
insert into MOCK_DATA (Genre, Genre_ID) values ('congue risus', 5);
insert into MOCK_DATA (Genre, Genre_ID) values ('hendrerit at', 6);
insert into MOCK_DATA (Genre, Genre_ID) values ('a', 7);
insert into MOCK_DATA (Genre, Genre_ID) values ('justo pellentesque viverra', 8);
insert into MOCK_DATA (Genre, Genre_ID) values ('sapien varius ut', 9);
insert into MOCK_DATA (Genre, Genre_ID) values ('luctus et', 10);
insert into MOCK_DATA (Genre, Genre_ID) values ('morbi sem', 11);
insert into MOCK_DATA (Genre, Genre_ID) values ('mauris enim leo', 12);
insert into MOCK_DATA (Genre, Genre_ID) values ('amet sapien', 13);
insert into MOCK_DATA (Genre, Genre_ID) values ('duis at velit', 14);
insert into MOCK_DATA (Genre, Genre_ID) values ('ridiculus', 15);
insert into MOCK_DATA (Genre, Genre_ID) values ('vulputate', 16);
insert into MOCK_DATA (Genre, Genre_ID) values ('in leo maecenas', 17);
insert into MOCK_DATA (Genre, Genre_ID) values ('diam cras pellentesque', 18);
insert into MOCK_DATA (Genre, Genre_ID) values ('lectus suspendisse potenti', 19);
insert into MOCK_DATA (Genre, Genre_ID) values ('sit', 20);
insert into MOCK_DATA (Genre, Genre_ID) values ('sit amet', 21);
insert into MOCK_DATA (Genre, Genre_ID) values ('faucibus orci luctus', 22);
insert into MOCK_DATA (Genre, Genre_ID) values ('ut', 23);
insert into MOCK_DATA (Genre, Genre_ID) values ('commodo vulputate', 24);
insert into MOCK_DATA (Genre, Genre_ID) values ('nunc rhoncus', 25);
insert into MOCK_DATA (Genre, Genre_ID) values ('sed', 26);
insert into MOCK_DATA (Genre, Genre_ID) values ('tempor turpis', 27);
insert into MOCK_DATA (Genre, Genre_ID) values ('sed magna', 28);
insert into MOCK_DATA (Genre, Genre_ID) values ('feugiat et', 29);
insert into MOCK_DATA (Genre, Genre_ID) values ('sit amet sem', 30);
insert into MOCK_DATA (Genre, Genre_ID) values ('pulvinar', 31);
insert into MOCK_DATA (Genre, Genre_ID) values ('vestibulum', 32);
insert into MOCK_DATA (Genre, Genre_ID) values ('nulla nunc', 33);
insert into MOCK_DATA (Genre, Genre_ID) values ('pharetra', 34);
insert into MOCK_DATA (Genre, Genre_ID) values ('ante ipsum', 35);
insert into MOCK_DATA (Genre, Genre_ID) values ('tellus in sagittis', 36);
insert into MOCK_DATA (Genre, Genre_ID) values ('duis aliquam', 37);
insert into MOCK_DATA (Genre, Genre_ID) values ('metus', 38);
insert into MOCK_DATA (Genre, Genre_ID) values ('risus semper porta', 39);
insert into MOCK_DATA (Genre, Genre_ID) values ('risus praesent', 40);
insert into MOCK_DATA (Genre, Genre_ID) values ('a suscipit', 41);
insert into MOCK_DATA (Genre, Genre_ID) values ('lacinia eget', 42);
insert into MOCK_DATA (Genre, Genre_ID) values ('id', 43);
insert into MOCK_DATA (Genre, Genre_ID) values ('posuere felis sed', 44);
insert into MOCK_DATA (Genre, Genre_ID) values ('natoque', 45);
insert into MOCK_DATA (Genre, Genre_ID) values ('justo', 46);
insert into MOCK_DATA (Genre, Genre_ID) values ('parturient', 47);
insert into MOCK_DATA (Genre, Genre_ID) values ('lacus morbi sem', 48);
insert into MOCK_DATA (Genre, Genre_ID) values ('parturient', 49);
insert into MOCK_DATA (Genre, Genre_ID) values ('curae', 50);
