SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

USE `pyo`;

insert into Prompts (Prompt, Prompt_ID) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 1);
insert into Prompts (Prompt, Prompt_ID) values ('Integer non velit.', 2);
insert into Prompts (Prompt, Prompt_ID) values ('Ut at dolor quis odio consequat varius.', 3);
insert into Prompts (Prompt, Prompt_ID) values ('Suspendisse potenti.', 4);
insert into Prompts (Prompt, Prompt_ID) values ('Etiam pretium iaculis justo.', 5);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla facilisi.', 6);
insert into Prompts (Prompt, Prompt_ID) values ('Cras non velit nec nisi vulputate nonummy.', 7);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla ac enim.', 8);
insert into Prompts (Prompt, Prompt_ID) values ('Praesent lectus.', 9);
insert into Prompts (Prompt, Prompt_ID) values ('Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 10);
insert into Prompts (Prompt, Prompt_ID) values ('Nam dui.', 11);
insert into Prompts (Prompt, Prompt_ID) values ('Praesent lectus.', 12);
insert into Prompts (Prompt, Prompt_ID) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 13);
insert into Prompts (Prompt, Prompt_ID) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 14);
insert into Prompts (Prompt, Prompt_ID) values ('In quis justo.', 15);
insert into Prompts (Prompt, Prompt_ID) values ('Duis consequat dui nec nisi volutpat eleifend.', 16);
insert into Prompts (Prompt, Prompt_ID) values ('Aenean lectus.', 17);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas ut massa quis augue luctus tincidunt.', 18);
insert into Prompts (Prompt, Prompt_ID) values ('Vivamus vestibulum sagittis sapien.', 19);
insert into Prompts (Prompt, Prompt_ID) values ('Vivamus vestibulum sagittis sapien.', 20);
insert into Prompts (Prompt, Prompt_ID) values ('Curabitur convallis.', 21);
insert into Prompts (Prompt, Prompt_ID) values ('Nunc purus.', 22);
insert into Prompts (Prompt, Prompt_ID) values ('Proin interdum mauris non ligula pellentesque ultrices.', 23);
insert into Prompts (Prompt, Prompt_ID) values ('Quisque porta volutpat erat.', 24);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi non lectus.', 25);
insert into Prompts (Prompt, Prompt_ID) values ('Nam dui.', 26);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas pulvinar lobortis est.', 27);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi vel lectus in quam fringilla rhoncus.', 28);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 29);
insert into Prompts (Prompt, Prompt_ID) values ('Pellentesque at nulla.', 30);
insert into Prompts (Prompt, Prompt_ID) values ('Nullam varius.', 31);
insert into Prompts (Prompt, Prompt_ID) values ('Donec ut mauris eget massa tempor convallis.', 32);
insert into Prompts (Prompt, Prompt_ID) values ('Nullam porttitor lacus at turpis.', 33);
insert into Prompts (Prompt, Prompt_ID) values ('Vestibulum ac est lacinia nisi venenatis tristique.', 34);
insert into Prompts (Prompt, Prompt_ID) values ('Proin risus.', 35);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 36);
insert into Prompts (Prompt, Prompt_ID) values ('Praesent lectus.', 37);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 38);
insert into Prompts (Prompt, Prompt_ID) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 39);
insert into Prompts (Prompt, Prompt_ID) values ('Quisque ut erat.', 40);
insert into Prompts (Prompt, Prompt_ID) values ('Vivamus vestibulum sagittis sapien.', 41);
insert into Prompts (Prompt, Prompt_ID) values ('In hac habitasse platea dictumst.', 42);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 43);
insert into Prompts (Prompt, Prompt_ID) values ('Aliquam quis turpis eget elit sodales scelerisque.', 44);
insert into Prompts (Prompt, Prompt_ID) values ('Proin eu mi.', 45);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 46);
insert into Prompts (Prompt, Prompt_ID) values ('Duis bibendum.', 47);
insert into Prompts (Prompt, Prompt_ID) values ('Ut at dolor quis odio consequat varius.', 48);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla facilisi.', 49);
insert into Prompts (Prompt, Prompt_ID) values ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 50);
insert into Prompts (Prompt, Prompt_ID) values ('Donec posuere metus vitae ipsum.', 51);

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;