insert into Prompts (Prompt, Prompt_ID) values ('Mauris sit amet eros.', 1);
insert into Prompts (Prompt, Prompt_ID) values ('Duis ac nibh.', 2);
insert into Prompts (Prompt, Prompt_ID) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 3);
insert into Prompts (Prompt, Prompt_ID) values ('Curabitur gravida nisi at nibh.', 4);
insert into Prompts (Prompt, Prompt_ID) values ('In sagittis dui vel nisl.', 5);
insert into Prompts (Prompt, Prompt_ID) values ('In hac habitasse platea dictumst.', 6);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 7);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi non quam nec dui luctus rutrum.', 8);
insert into Prompts (Prompt, Prompt_ID) values ('Etiam justo.', 9);
insert into Prompts (Prompt, Prompt_ID) values ('Mauris sit amet eros.', 10);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas pulvinar lobortis est.', 11);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 12);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla facilisi.', 13);
insert into Prompts (Prompt, Prompt_ID) values ('Pellentesque eget nunc.', 14);
insert into Prompts (Prompt, Prompt_ID) values ('Nullam porttitor lacus at turpis.', 15);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi vel lectus in quam fringilla rhoncus.', 16);
insert into Prompts (Prompt, Prompt_ID) values ('Nam dui.', 17);
insert into Prompts (Prompt, Prompt_ID) values ('Pellentesque eget nunc.', 18);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 19);
insert into Prompts (Prompt, Prompt_ID) values ('In hac habitasse platea dictumst.', 20);
insert into Prompts (Prompt, Prompt_ID) values ('Nullam varius.', 21);
insert into Prompts (Prompt, Prompt_ID) values ('Donec ut mauris eget massa tempor convallis.', 22);
insert into Prompts (Prompt, Prompt_ID) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 23);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla ut erat id mauris vulputate elementum.', 24);
insert into Prompts (Prompt, Prompt_ID) values ('Pellentesque viverra pede ac diam.', 25);
insert into Prompts (Prompt, Prompt_ID) values ('Phasellus id sapien in sapien iaculis congue.', 26);
insert into Prompts (Prompt, Prompt_ID) values ('Aliquam non mauris.', 27);
insert into Prompts (Prompt, Prompt_ID) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 28);
insert into Prompts (Prompt, Prompt_ID) values ('Etiam vel augue.', 29);
insert into Prompts (Prompt, Prompt_ID) values ('Aliquam quis turpis eget elit sodales scelerisque.', 30);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas ut massa quis augue luctus tincidunt.', 31);
insert into Prompts (Prompt, Prompt_ID) values ('Donec posuere metus vitae ipsum.', 32);
insert into Prompts (Prompt, Prompt_ID) values ('Praesent lectus.', 33);
insert into Prompts (Prompt, Prompt_ID) values ('Nunc rhoncus dui vel sem.', 34);
insert into Prompts (Prompt, Prompt_ID) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 35);
insert into Prompts (Prompt, Prompt_ID) values ('Mauris ullamcorper purus sit amet nulla.', 36);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi non lectus.', 37);
insert into Prompts (Prompt, Prompt_ID) values ('Nunc purus.', 38);
insert into Prompts (Prompt, Prompt_ID) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 39);
insert into Prompts (Prompt, Prompt_ID) values ('Duis ac nibh.', 40);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 41);
insert into Prompts (Prompt, Prompt_ID) values ('Cras pellentesque volutpat dui.', 42);
insert into Prompts (Prompt, Prompt_ID) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 43);
insert into Prompts (Prompt, Prompt_ID) values ('Quisque porta volutpat erat.', 44);
insert into Prompts (Prompt, Prompt_ID) values ('Integer non velit.', 45);
insert into Prompts (Prompt, Prompt_ID) values ('Integer ac leo.', 46);
insert into Prompts (Prompt, Prompt_ID) values ('Integer tincidunt ante vel ipsum.', 47);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi a ipsum.', 48);
insert into Prompts (Prompt, Prompt_ID) values ('Vestibulum sed magna at nunc commodo placerat.', 49);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla ut erat id mauris vulputate elementum.', 50);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla nisl.', 51);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla facilisi.', 52);
insert into Prompts (Prompt, Prompt_ID) values ('Duis aliquam convallis nunc.', 53);
insert into Prompts (Prompt, Prompt_ID) values ('Proin at turpis a pede posuere nonummy.', 54);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 55);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla nisl.', 56);
insert into Prompts (Prompt, Prompt_ID) values ('Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 57);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla mollis molestie lorem.', 58);
insert into Prompts (Prompt, Prompt_ID) values ('Phasellus in felis.', 59);
insert into Prompts (Prompt, Prompt_ID) values ('Curabitur convallis.', 60);
insert into Prompts (Prompt, Prompt_ID) values ('Suspendisse accumsan tortor quis turpis.', 61);
insert into Prompts (Prompt, Prompt_ID) values ('In hac habitasse platea dictumst.', 62);
insert into Prompts (Prompt, Prompt_ID) values ('In hac habitasse platea dictumst.', 63);
insert into Prompts (Prompt, Prompt_ID) values ('Duis bibendum.', 64);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 65);
insert into Prompts (Prompt, Prompt_ID) values ('Aenean sit amet justo.', 66);
insert into Prompts (Prompt, Prompt_ID) values ('Suspendisse potenti.', 67);
insert into Prompts (Prompt, Prompt_ID) values ('Duis aliquam convallis nunc.', 68);
insert into Prompts (Prompt, Prompt_ID) values ('Nunc purus.', 69);
insert into Prompts (Prompt, Prompt_ID) values ('Cras non velit nec nisi vulputate nonummy.', 70);
insert into Prompts (Prompt, Prompt_ID) values ('Aenean lectus.', 71);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas ut massa quis augue luctus tincidunt.', 72);
insert into Prompts (Prompt, Prompt_ID) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 73);
insert into Prompts (Prompt, Prompt_ID) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 74);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 75);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 76);
insert into Prompts (Prompt, Prompt_ID) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 77);
insert into Prompts (Prompt, Prompt_ID) values ('Phasellus id sapien in sapien iaculis congue.', 78);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi a ipsum.', 79);
insert into Prompts (Prompt, Prompt_ID) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 80);
insert into Prompts (Prompt, Prompt_ID) values ('Mauris sit amet eros.', 81);
insert into Prompts (Prompt, Prompt_ID) values ('In sagittis dui vel nisl.', 82);
insert into Prompts (Prompt, Prompt_ID) values ('Curabitur gravida nisi at nibh.', 83);
insert into Prompts (Prompt, Prompt_ID) values ('Nunc nisl.', 84);
insert into Prompts (Prompt, Prompt_ID) values ('In hac habitasse platea dictumst.', 85);
insert into Prompts (Prompt, Prompt_ID) values ('Aenean auctor gravida sem.', 86);
insert into Prompts (Prompt, Prompt_ID) values ('Cras in purus eu magna vulputate luctus.', 87);
insert into Prompts (Prompt, Prompt_ID) values ('In blandit ultrices enim.', 88);
insert into Prompts (Prompt, Prompt_ID) values ('Suspendisse potenti.', 89);
insert into Prompts (Prompt, Prompt_ID) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 90);
insert into Prompts (Prompt, Prompt_ID) values ('Phasellus sit amet erat.', 91);
insert into Prompts (Prompt, Prompt_ID) values ('Proin risus.', 92);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla ut erat id mauris vulputate elementum.', 93);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi quis tortor id nulla ultrices aliquet.', 94);
insert into Prompts (Prompt, Prompt_ID) values ('Proin risus.', 95);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi quis tortor id nulla ultrices aliquet.', 96);
insert into Prompts (Prompt, Prompt_ID) values ('Morbi vel lectus in quam fringilla rhoncus.', 97);
insert into Prompts (Prompt, Prompt_ID) values ('Donec semper sapien a libero.', 98);
insert into Prompts (Prompt, Prompt_ID) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 99);
insert into Prompts (Prompt, Prompt_ID) values ('Nulla suscipit ligula in lacus.', 100);
