SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

USE `pyo`;

insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('4lqKRKXULMMcfit48DU14', 'cursus', '6mnFSLEOJFXnhfu1GJEJG', '39');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7alVPPJXKSVwbdc284STJ', 'rutrum ac lobortis vel', '2buOUUZBNUYwfcn5G2ASK', '41');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7gtPFLHPLIRfgzk8BNRTB', 'risus', '7pgMHXXPSDHteiv3FOXPP', '31');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7jyNTUZFDJTtjgf07W6VH', 'arcu sed augue', '5dvARBKLTQVknca26CRGJ', '20');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('3nzHXATNUFJcxbu73YV3A', 'luctus nec molestie', '8soPNQXIUPRqxzj47KNP5', '17');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('3xjHVYUEKUEdhna5Y45M2', 'duis mattis egestas', '0omGXITKKJBanvg382CZH', '37');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('5vnPRRZFBUAejob0BERVK', 'tortor id nulla ultrices', '0vpYLLBSAOOpust2IKSTL', '36');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('1ejAYYWFUAIefoy4OCE98', 'molestie sed justo pellentesque', '9amDQOUKHHRtpsp4X4Z0D', '50');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7psVYOXSYYLvuac2XYTJH', 'in hac habitasse platea', '5hwDPBMDWWEhcck304L49', '6');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0ttRSPGNXNFlmfb80BN4L', 'ut', '7ngMRWDFGCOtfrm9CQZO9', '26');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('9uvYWTOUXOCjtxv4UBB6C', 'vel pede', '3wlGGXNADQAcwca5YS9T1', '45');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('9rcKQKBGRYCevrm9JHV1I', 'consectetuer eget rutrum at', '4cjZXLOSEMCsbft0O2GY2', '11');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('6itSYKVOGSPzrbq4BUD0B', 'blandit', '5klJUHSMWKGwfrt9DQZPG', '29');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('2wcXFBGHLZRdrby4U24GS', 'vitae nisl aenean lectus', '7boVCWUKABCfmvv5SUQQZ', '47');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('9feGOEIOGLUmocl5JHAU5', 'massa id', '8dvKZMFTPYHlmgn8V8NBZ', '21');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7qaOGWBFHDNnybb3SNE4J', 'praesent lectus vestibulum', '5suOAJNMOOVhfzs0EKS6Y', '1');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('2dzKIXEUASFfjtw8291F6', 'quis', '7eyGGZTMQZGpmdw0JL06L', '49');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('6huQVYVEEKLepnj6KX6HM', 'rhoncus aliquam lacus morbi', '6bdAJZDVJUPwrea0D899N', '33');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0hhGOJFGLSRfrdg3KVPBF', 'vel', '8xaIOWQNKCIcibt54FSX3', '42');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0ysSWXZFRPXdeqa34ZPNQ', 'lectus pellentesque at', '7cnKNSLPKQBdfef53UNX7', '34');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('8mbMWHSRGKKfdrm36106F', 'mus vivamus', '6feFMNJQVGOmngg3PJKWC', '14');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7unAKVNENSVnaew2A4LYK', 'ultrices', '0gsEWSTWQGWcpuj2FGYSJ', '19');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('9kzZGZGLCYDirqz23VMRO', 'vestibulum proin', '8ghUUAMTOCXykye2E94AZ', '38');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('3zzJWNHAELQgtyp38AGE2', 'orci nullam molestie', '2sfVGDYNBJXhycf3V7820', '25');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0fjLHSBHAIEwgox1PN96G', 'mauris', '9tcQURHHKLFdehd8TFY4C', '23');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0odXWQXIHOGjgvo1YFG6W', 'lobortis', '7auSMNCMHBPlwqr7TP5NV', '2');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('4ctFKPIOEWHgkvo6OKA2A', 'ut', '8mmHEIYSNCRuyrx1U949Q', '15');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0ptVBJRCTUAkjof14ORKN', 'praesent', '2tsPPNGWTBOzwsq3T70NP', '13');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('5wfVIYYODEHcgis59RU5U', 'ridiculus mus', '6brMAQIEFROtqcx0JX249', '48');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7iwQCKVVRERmfwz55LUDT', 'quis', '0ycZXFIZXZXnhpf4E2PNP', '4');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7qeHHLPSGVHkyte90PFA0', 'auctor sed tristique', '2ocQBPTBNWHfnda39NPNG', '18');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('9uoUHJIZQMQdnyo26F3BX', 'nunc vestibulum ante', '5tkQGKPSRVIrbml16SVT8', '40');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('2smANSIAATOvqhq9IV1CN', 'mauris laoreet', '0joVFQEGIKOhkoo42NPOH', '24');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7gdRKUALDQUinux9YHERE', 'vestibulum aliquet ultrices', '5rbFCXTUYYDgseo2ILA24', '12');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('9igZRGDXORGxjni6XCOXJ', 'quam turpis', '8jhLQHDFMQBfbbv50YSJX', '22');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('3doSUGZYMFFoblu2SVDB8', 'sit amet eleifend', '4wjKGJEMBKZubra46XSLU', '35');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('8xwZNOPKKOUcsia5R0SSA', 'eu interdum', '9zdHJGVVNRDzvgr4OFKEC', '16');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0eyUHJVFFSIklwe4WMFLD', 'nunc vestibulum ante ipsum', '5lmTJUZFKOJvour042ITU', '46');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('6sbGXPBEEQUhayu3KDSTD', 'vestibulum velit id', '8ewFMJGGUIWfmrl5LKAVO', '30');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('4bvOAIXHMRIffoh593M5L', 'auctor gravida sem', '0ijDPPEOZFOjech5DJL4K', '9');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7jkEBSTIJUYyfnd6FCOK3', 'ultrices', '0xbYZUOGLWRyjui1RO1RO', '27');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('7teTBTFBMRTuwmn6KUL19', 'mauris', '6uaQZGKKZODqbha22BRQF', '7');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('1yhDUNPVCLXndfb1QBN3V', 'odio condimentum', '2nmEPFTYSYNbkzx6GT9V4', '44');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0kbRSGBYSZWtmno3T4R3X', 'eget', '0ovTXBBDMUNvkts8R8NG9', '8');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('4leXLXUMJFHykio6L4YGM', 'quisque id', '8nzFFMHXOLBxwir3NW54R', '43');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('9tsXCFYOENZlnkq9QLO96', 'vel nulla', '3ihVPITXFEEvqbl08UQPH', '28');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('1vmFYEOOUJNqsyu67EAGU', 'integer tincidunt', '5dgBQCHSNFXotci3LCF5Z', '10');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('8rpAHLWYJSGqhqp8Y92L3', 'est', '4acPWGJJCLFlqcs79479W', '32');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('9avOPDHIVNNhqko5FV03D', 'vitae consectetuer eget rutrum', '0nlPZHCUDDZspjj5E4XS5', '5');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values ('0maQJXJXLMWdyfd85QLRC', 'volutpat in', '9snVUEGTHJNxpjj3MNLP4', '3');

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;