insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (1, 'non mauris morbi', '7boVCWUKABCfmvv5SUQQZ', '9');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (2, 'ut', '0ijDPPEOZFOjech5DJL4K', '36');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (3, 'quis lectus suspendisse potenti', '5suOAJNMOOVhfzs0EKS6Y', '47');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (4, 'et tempus semper est', '3wlGGXNADQAcwca5YS9T1', '34');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (5, 'nulla', '5klJUHSMWKGwfrt9DQZPG', '5');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (6, 'neque libero convallis', '0joVFQEGIKOhkoo42NPOH', '28');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (7, 'condimentum', '2nmEPFTYSYNbkzx6GT9V4', '23');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (8, 'rutrum rutrum', '0xbYZUOGLWRyjui1RO1RO', '3');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (9, 'sollicitudin mi sit', '7auSMNCMHBPlwqr7TP5NV', '19');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (10, 'habitasse platea', '5lmTJUZFKOJvour042ITU', '4');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (11, 'scelerisque mauris sit amet', '8nzFFMHXOLBxwir3NW54R', '45');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (12, 'faucibus orci luctus et', '6mnFSLEOJFXnhfu1GJEJG', '12');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (13, 'pede justo lacinia eget', '7pgMHXXPSDHteiv3FOXPP', '32');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (14, 'porttitor lorem id', '3ihVPITXFEEvqbl08UQPH', '31');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (15, 'sed ante vivamus tortor', '2sfVGDYNBJXhycf3V7820', '21');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (16, 'vestibulum', '0gsEWSTWQGWcpuj2FGYSJ', '30');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (17, 'urna ut', '0ycZXFIZXZXnhpf4E2PNP', '11');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (18, 'elementum in hac habitasse', '8xaIOWQNKCIcibt54FSX3', '8');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (19, 'vitae mattis', '0nlPZHCUDDZspjj5E4XS5', '37');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (20, 'maecenas tincidunt', '9amDQOUKHHRtpsp4X4Z0D', '25');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (21, 'pellentesque eget nunc donec', '7eyGGZTMQZGpmdw0JL06L', '27');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (22, 'vel sem sed sagittis', '5rbFCXTUYYDgseo2ILA24', '7');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (23, 'purus', '6uaQZGKKZODqbha22BRQF', '22');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (24, 'adipiscing lorem vitae', '4cjZXLOSEMCsbft0O2GY2', '29');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (25, 'quisque id', '8ghUUAMTOCXykye2E94AZ', '38');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (26, 'venenatis', '6bdAJZDVJUPwrea0D899N', '6');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (27, 'dictumst etiam', '8dvKZMFTPYHlmgn8V8NBZ', '20');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (28, 'ut', '0ovTXBBDMUNvkts8R8NG9', '1');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (29, 'morbi ut odio', '6feFMNJQVGOmngg3PJKWC', '15');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (30, 'ipsum ac tellus semper', '8jhLQHDFMQBfbbv50YSJX', '17');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (31, 'luctus', '8mmHEIYSNCRuyrx1U949Q', '39');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (32, 'et', '8soPNQXIUPRqxzj47KNP5', '42');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (33, 'eu nibh quisque', '2ocQBPTBNWHfnda39NPNG', '43');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (34, 'rhoncus', '0omGXITKKJBanvg382CZH', '10');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (35, 'blandit mi', '6brMAQIEFROtqcx0JX249', '35');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (36, 'quis lectus suspendisse', '7cnKNSLPKQBdfef53UNX7', '14');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (37, 'molestie', '7ngMRWDFGCOtfrm9CQZO9', '2');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (38, 'libero rutrum', '4acPWGJJCLFlqcs79479W', '13');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (39, 'sapien', '5tkQGKPSRVIrbml16SVT8', '48');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (40, 'euismod scelerisque quam turpis', '2buOUUZBNUYwfcn5G2ASK', '40');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (41, 'nulla sed accumsan', '2tsPPNGWTBOzwsq3T70NP', '26');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (42, 'quisque erat eros viverra', '0vpYLLBSAOOpust2IKSTL', '41');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (43, 'sit', '9zdHJGVVNRDzvgr4OFKEC', '33');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (44, 'quis lectus suspendisse potenti', '5dgBQCHSNFXotci3LCF5Z', '49');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (45, 'ac diam cras', '5dvARBKLTQVknca26CRGJ', '16');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (46, 'id', '4wjKGJEMBKZubra46XSLU', '50');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (47, 'turpis enim blandit mi', '9tcQURHHKLFdehd8TFY4C', '18');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (48, 'ut at dolor quis', '9snVUEGTHJNxpjj3MNLP4', '24');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (49, 'in est risus auctor', '8ewFMJGGUIWfmrl5LKAVO', '46');
insert into Songs (Song_ID, Name, artist_ID, Genre_ID) values (50, 'quis libero nullam sit', '5hwDPBMDWWEhcck304L49', '44');
